/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import com.atlassian.jira.rest.client.v2.model.AttachmentArchiveEntry;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AttachmentArchive
 */
public class AttachmentArchiveTest {
    private final AttachmentArchive model = new AttachmentArchive();

    /**
     * Model tests for AttachmentArchive
     */
    @Test
    public void testAttachmentArchive() {
        // TODO: test AttachmentArchive
    }

    /**
     * Test the property 'moreAvailable'
     */
    @Test
    public void moreAvailableTest() {
        // TODO: test moreAvailable
    }

    /**
     * Test the property 'totalNumberOfEntriesAvailable'
     */
    @Test
    public void totalNumberOfEntriesAvailableTest() {
        // TODO: test totalNumberOfEntriesAvailable
    }

    /**
     * Test the property 'totalEntryCount'
     */
    @Test
    public void totalEntryCountTest() {
        // TODO: test totalEntryCount
    }

    /**
     * Test the property 'entries'
     */
    @Test
    public void entriesTest() {
        // TODO: test entries
    }

}
