/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomFieldContextDefaultValueCascadingOption
 */
public class CustomFieldContextDefaultValueCascadingOptionTest {
    private final CustomFieldContextDefaultValueCascadingOption model = new CustomFieldContextDefaultValueCascadingOption();

    /**
     * Model tests for CustomFieldContextDefaultValueCascadingOption
     */
    @Test
    public void testCustomFieldContextDefaultValueCascadingOption() {
        // TODO: test CustomFieldContextDefaultValueCascadingOption
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

    /**
     * Test the property 'optionId'
     */
    @Test
    public void optionIdTest() {
        // TODO: test optionId
    }

    /**
     * Test the property 'cascadingOptionId'
     */
    @Test
    public void cascadingOptionIdTest() {
        // TODO: test cascadingOptionId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
