/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import com.atlassian.jira.rest.client.v2.model.CustomFieldContextDefaultValueCascadingOption;
import com.atlassian.jira.rest.client.v2.model.CustomFieldContextDefaultValueMultipleOption;
import com.atlassian.jira.rest.client.v2.model.CustomFieldContextDefaultValueSingleOption;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomFieldContextDefaultValue
 */
public class CustomFieldContextDefaultValueTest {
    private final CustomFieldContextDefaultValue model = new CustomFieldContextDefaultValue();

    /**
     * Model tests for CustomFieldContextDefaultValue
     */
    @Test
    public void testCustomFieldContextDefaultValue() {
        // TODO: test CustomFieldContextDefaultValue
    }

    /**
     * Test the property 'contextId'
     */
    @Test
    public void contextIdTest() {
        // TODO: test contextId
    }

    /**
     * Test the property 'optionId'
     */
    @Test
    public void optionIdTest() {
        // TODO: test optionId
    }

    /**
     * Test the property 'cascadingOptionId'
     */
    @Test
    public void cascadingOptionIdTest() {
        // TODO: test cascadingOptionId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'optionIds'
     */
    @Test
    public void optionIdsTest() {
        // TODO: test optionIds
    }

}
