/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectFeature
 */
public class ProjectFeatureTest {
    private final ProjectFeature model = new ProjectFeature();

    /**
     * Model tests for ProjectFeature
     */
    @Test
    public void testProjectFeature() {
        // TODO: test ProjectFeature
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'toggleLocked'
     */
    @Test
    public void toggleLockedTest() {
        // TODO: test toggleLocked
    }

    /**
     * Test the property 'feature'
     */
    @Test
    public void featureTest() {
        // TODO: test feature
    }

    /**
     * Test the property 'featureCategory'
     */
    @Test
    public void featureCategoryTest() {
        // TODO: test featureCategory
    }

    /**
     * Test the property 'prerequisites'
     */
    @Test
    public void prerequisitesTest() {
        // TODO: test prerequisites
    }

    /**
     * Test the property 'localisedName'
     */
    @Test
    public void localisedNameTest() {
        // TODO: test localisedName
    }

    /**
     * Test the property 'localisedDescription'
     */
    @Test
    public void localisedDescriptionTest() {
        // TODO: test localisedDescription
    }

    /**
     * Test the property 'imageUri'
     */
    @Test
    public void imageUriTest() {
        // TODO: test imageUri
    }

}
