/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Default value for a multi-select custom field.
 */
@ApiModel(description = "Default value for a multi-select custom field.")
@JsonPropertyOrder({
  CustomFieldContextDefaultValueMultipleOption.JSON_PROPERTY_CONTEXT_ID,
  CustomFieldContextDefaultValueMultipleOption.JSON_PROPERTY_OPTION_IDS,
  CustomFieldContextDefaultValueMultipleOption.JSON_PROPERTY_TYPE
})
@JsonTypeName("CustomFieldContextDefaultValueMultipleOption")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-16T21:45:04.339922+09:00[Asia/Seoul]")
public class CustomFieldContextDefaultValueMultipleOption {
  public static final String JSON_PROPERTY_CONTEXT_ID = "contextId";
  private String contextId;

  public static final String JSON_PROPERTY_OPTION_IDS = "optionIds";
  private List<String> optionIds = new ArrayList<>();

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;


  public CustomFieldContextDefaultValueMultipleOption contextId(String contextId) {
    
    this.contextId = contextId;
    return this;
  }

   /**
   * The ID of the context.
   * @return contextId
  **/
  @ApiModelProperty(required = true, value = "The ID of the context.")
  @JsonProperty(JSON_PROPERTY_CONTEXT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getContextId() {
    return contextId;
  }


  public void setContextId(String contextId) {
    this.contextId = contextId;
  }


  public CustomFieldContextDefaultValueMultipleOption optionIds(List<String> optionIds) {
    
    this.optionIds = optionIds;
    return this;
  }

  public CustomFieldContextDefaultValueMultipleOption addOptionIdsItem(String optionIdsItem) {
    this.optionIds.add(optionIdsItem);
    return this;
  }

   /**
   * The list of IDs of the default options.
   * @return optionIds
  **/
  @ApiModelProperty(required = true, value = "The list of IDs of the default options.")
  @JsonProperty(JSON_PROPERTY_OPTION_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getOptionIds() {
    return optionIds;
  }


  public void setOptionIds(List<String> optionIds) {
    this.optionIds = optionIds;
  }


  public CustomFieldContextDefaultValueMultipleOption type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFieldContextDefaultValueMultipleOption customFieldContextDefaultValueMultipleOption = (CustomFieldContextDefaultValueMultipleOption) o;
    return Objects.equals(this.contextId, customFieldContextDefaultValueMultipleOption.contextId) &&
        Objects.equals(this.optionIds, customFieldContextDefaultValueMultipleOption.optionIds) &&
        Objects.equals(this.type, customFieldContextDefaultValueMultipleOption.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contextId, optionIds, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFieldContextDefaultValueMultipleOption {\n");
    sb.append("    contextId: ").append(toIndentedString(contextId)).append("\n");
    sb.append("    optionIds: ").append(toIndentedString(optionIds)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

