/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.v2.model.HierarchyLevel;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The project issue type hierarchy.
 */
@ApiModel(description = "The project issue type hierarchy.")
@JsonPropertyOrder({
  Hierarchy.JSON_PROPERTY_BASE_LEVEL_ID,
  Hierarchy.JSON_PROPERTY_LEVELS
})
@JsonTypeName("Hierarchy")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-16T21:45:04.339922+09:00[Asia/Seoul]")
public class Hierarchy {
  public static final String JSON_PROPERTY_BASE_LEVEL_ID = "baseLevelId";
  private Long baseLevelId;

  public static final String JSON_PROPERTY_LEVELS = "levels";
  private List<HierarchyLevel> levels = null;


  public Hierarchy baseLevelId(Long baseLevelId) {
    
    this.baseLevelId = baseLevelId;
    return this;
  }

   /**
   * The ID of the base level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).
   * @return baseLevelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the base level. This property is deprecated, see [Change notice: Removing hierarchy level IDs from next-gen APIs](https://developer.atlassian.com/cloud/jira/platform/change-notice-removing-hierarchy-level-ids-from-next-gen-apis/).")
  @JsonProperty(JSON_PROPERTY_BASE_LEVEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBaseLevelId() {
    return baseLevelId;
  }


  public void setBaseLevelId(Long baseLevelId) {
    this.baseLevelId = baseLevelId;
  }


   /**
   * Details about the hierarchy level.
   * @return levels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details about the hierarchy level.")
  @JsonProperty(JSON_PROPERTY_LEVELS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<HierarchyLevel> getLevels() {
    return levels;
  }




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hierarchy hierarchy = (Hierarchy) o;
    return Objects.equals(this.baseLevelId, hierarchy.baseLevelId) &&
        Objects.equals(this.levels, hierarchy.levels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseLevelId, levels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hierarchy {\n");
    sb.append("    baseLevelId: ").append(toIndentedString(baseLevelId)).append("\n");
    sb.append("    levels: ").append(toIndentedString(levels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

