/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.atlassian.jira.rest.client.v2.model.WorkflowCompoundCondition;
import com.atlassian.jira.rest.client.v2.model.WorkflowSimpleCondition;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * The workflow conditions tree.
 */
@ApiModel(description = "The workflow conditions tree.")
@JsonPropertyOrder({
  WorkflowConditionBean.JSON_PROPERTY_TYPE,
  WorkflowConditionBean.JSON_PROPERTY_CONFIGURATION,
  WorkflowConditionBean.JSON_PROPERTY_NODE_TYPE,
  WorkflowConditionBean.JSON_PROPERTY_OPERATOR,
  WorkflowConditionBean.JSON_PROPERTY_CONDITIONS
})
@JsonTypeName("WorkflowConditionBean")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-16T21:45:04.339922+09:00[Asia/Seoul]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "nodeType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = WorkflowCompoundCondition.class, name = "WorkflowCompoundCondition"),
  @JsonSubTypes.Type(value = WorkflowSimpleCondition.class, name = "WorkflowSimpleCondition"),
  @JsonSubTypes.Type(value = WorkflowCompoundCondition.class, name = "compound"),
  @JsonSubTypes.Type(value = WorkflowSimpleCondition.class, name = "simple"),
})

public class WorkflowConditionBean {
  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public static final String JSON_PROPERTY_CONFIGURATION = "configuration";
  private Object _configuration;

  public static final String JSON_PROPERTY_NODE_TYPE = "nodeType";
  protected String nodeType;

  /**
   * The conditions operator.
   */
  public enum OperatorEnum {
    AND("AND"),
    
    OR("OR");

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  private OperatorEnum operator;

  public static final String JSON_PROPERTY_CONDITIONS = "conditions";
  private List<WorkflowConditionBean> conditions = new ArrayList<>();


  public WorkflowConditionBean type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of the transition rule.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of the transition rule.")
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public WorkflowConditionBean _configuration(Object _configuration) {
    
    this._configuration = _configuration;
    return this;
  }

   /**
   * The configuration of the transition rule. This is currently returned only for some of the rule types. Availability of this property is subject to change.
   * @return _configuration
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The configuration of the transition rule. This is currently returned only for some of the rule types. Availability of this property is subject to change.")
  @JsonProperty(JSON_PROPERTY_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getConfiguration() {
    return _configuration;
  }


  public void setConfiguration(Object _configuration) {
    this._configuration = _configuration;
  }


  public WorkflowConditionBean nodeType(String nodeType) {
    
    this.nodeType = nodeType;
    return this;
  }

   /**
   * Get nodeType
   * @return nodeType
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_NODE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNodeType() {
    return nodeType;
  }


  public void setNodeType(String nodeType) {
    this.nodeType = nodeType;
  }


  public WorkflowConditionBean operator(OperatorEnum operator) {
    
    this.operator = operator;
    return this;
  }

   /**
   * The conditions operator.
   * @return operator
  **/
  @ApiModelProperty(required = true, value = "The conditions operator.")
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OperatorEnum getOperator() {
    return operator;
  }


  public void setOperator(OperatorEnum operator) {
    this.operator = operator;
  }


  public WorkflowConditionBean conditions(List<WorkflowConditionBean> conditions) {
    
    this.conditions = conditions;
    return this;
  }

  public WorkflowConditionBean addConditionsItem(WorkflowConditionBean conditionsItem) {
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * The list of workflow conditions.
   * @return conditions
  **/
  @ApiModelProperty(required = true, value = "The list of workflow conditions.")
  @JsonProperty(JSON_PROPERTY_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<WorkflowConditionBean> getConditions() {
    return conditions;
  }


  public void setConditions(List<WorkflowConditionBean> conditions) {
    this.conditions = conditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowConditionBean workflowConditionBean = (WorkflowConditionBean) o;
    return Objects.equals(this.type, workflowConditionBean.type) &&
        Objects.equals(this._configuration, workflowConditionBean._configuration) &&
        Objects.equals(this.nodeType, workflowConditionBean.nodeType) &&
        Objects.equals(this.operator, workflowConditionBean.operator) &&
        Objects.equals(this.conditions, workflowConditionBean.conditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, _configuration, nodeType, operator, conditions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowConditionBean {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    nodeType: ").append(toIndentedString(nodeType)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

