/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.EntityProperty;
import com.atlassian.jira.rest.client.v2.model.OperationMessage;
import com.atlassian.jira.rest.client.v2.model.PropertyKeys;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppPropertiesApi
 */
@Ignore
public class AppPropertiesApiTest {

    private final AppPropertiesApi api = new AppPropertiesApi();

    
    /**
     * Delete app property
     *
     * Deletes an app&#39;s property.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request.
     */
    @Test
    public void addonPropertiesResourceDeleteAddonPropertyDeleteTest()  {
        String addonKey = null;
        String propertyKey = null;
        api.addonPropertiesResourceDeleteAddonPropertyDelete(addonKey, propertyKey).block();

        // TODO: test validations
    }
    
    /**
     * Get app properties
     *
     * Gets all the properties of an app.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request.
     */
    @Test
    public void addonPropertiesResourceGetAddonPropertiesGetTest()  {
        String addonKey = null;
        PropertyKeys response = api.addonPropertiesResourceGetAddonPropertiesGet(addonKey).block();

        // TODO: test validations
    }
    
    /**
     * Get app property
     *
     * Returns the key and value of an app&#39;s property.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request.
     */
    @Test
    public void addonPropertiesResourceGetAddonPropertyGetTest()  {
        String addonKey = null;
        String propertyKey = null;
        EntityProperty response = api.addonPropertiesResourceGetAddonPropertyGet(addonKey, propertyKey).block();

        // TODO: test validations
    }
    
    /**
     * Set app property
     *
     * Sets the value of an app&#39;s property. Use this resource to store custom data for your app.  The value of the request body must be a [valid](http://tools.ietf.org/html/rfc4627), non-empty JSON blob. The maximum length is 32768 characters.  **[Permissions](#permissions) required:** Only a Connect app whose key matches &#x60;addonKey&#x60; can make this request.
     */
    @Test
    public void addonPropertiesResourcePutAddonPropertyPutTest()  {
        String addonKey = null;
        String propertyKey = null;
        Object body = null;
        OperationMessage response = api.addonPropertiesResourcePutAddonPropertyPut(addonKey, propertyKey, body).block();

        // TODO: test validations
    }
    
}
