/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.AuditRecords;
import java.time.OffsetDateTime;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuditRecordsApi
 */
@Ignore
public class AuditRecordsApiTest {

    private final AuditRecordsApi api = new AuditRecordsApi();

    
    /**
     * Get audit records
     *
     * Returns a list of audit records. The list can be filtered to include items:   *  containing a string in at least one field. For example, providing *up* will return all audit records where one or more fields contains words such as *update*.  *  created on or after a date and time.  *  created or or before a date and time.  *  created during a time period.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getAuditRecordsTest()  {
        Integer offset = null;
        Integer limit = null;
        String filter = null;
        OffsetDateTime from = null;
        OffsetDateTime to = null;
        AuditRecords response = api.getAuditRecords(offset, limit, filter, from, to).block();

        // TODO: test validations
    }
    
}
