/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.ConnectModules;
import com.atlassian.jira.rest.client.v2.model.ErrorMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DynamicModulesApi
 */
@Ignore
public class DynamicModulesApiTest {

    private final DynamicModulesApi api = new DynamicModulesApi();

    
    /**
     * Get modules
     *
     * Returns all modules registered dynamically by the calling app.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     */
    @Test
    public void dynamicModulesResourceGetModulesGetTest()  {
        ConnectModules response = api.dynamicModulesResourceGetModulesGet().block();

        // TODO: test validations
    }
    
    /**
     * Register modules
     *
     * Registers a list of modules.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     */
    @Test
    public void dynamicModulesResourceRegisterModulesPostTest()  {
        ConnectModules connectModules = null;
        api.dynamicModulesResourceRegisterModulesPost(connectModules).block();

        // TODO: test validations
    }
    
    /**
     * Remove modules
     *
     * Remove all or a list of modules registered by the calling app.  **[Permissions](#permissions) required:** Only Connect apps can make this request.
     */
    @Test
    public void dynamicModulesResourceRemoveModulesDeleteTest()  {
        List<String> moduleKey = null;
        api.dynamicModulesResourceRemoveModulesDelete(moduleKey).block();

        // TODO: test validations
    }
    
}
