/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.DefaultShareScope;
import com.atlassian.jira.rest.client.v2.model.SharePermission;
import com.atlassian.jira.rest.client.v2.model.SharePermissionInputBean;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FilterSharingApi
 */
@Ignore
public class FilterSharingApiTest {

    private final FilterSharingApi api = new FilterSharingApi();

    
    /**
     * Add share permission
     *
     * Add a share permissions to a filter. If you add a global share permission (one for all logged-in users or the public) it will overwrite all share permissions for the filter.  Be aware that this operation uses different objects for updating share permissions compared to [Update filter](#api-rest-api-2-filter-id-put).  **[Permissions](#permissions) required:** *Share dashboards and filters* [global permission](https://confluence.atlassian.com/x/x4dKLg) and the user must own the filter.
     */
    @Test
    public void addSharePermissionTest()  {
        Long id = null;
        SharePermissionInputBean sharePermissionInputBean = null;
        List<SharePermission> response = api.addSharePermission(id, sharePermissionInputBean).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Delete share permission
     *
     * Deletes a share permission from a filter.  **[Permissions](#permissions) required:** Permission to access Jira and the user must own the filter.
     */
    @Test
    public void deleteSharePermissionTest()  {
        Long id = null;
        Long permissionId = null;
        api.deleteSharePermission(id, permissionId).block();

        // TODO: test validations
    }
    
    /**
     * Get default share scope
     *
     * Returns the default sharing settings for new filters and dashboards for a user.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void getDefaultShareScopeTest()  {
        DefaultShareScope response = api.getDefaultShareScope().block();

        // TODO: test validations
    }
    
    /**
     * Get share permission
     *
     * Returns a share permission for a filter. A filter can be shared with groups, projects, all logged-in users, or the public. Sharing with all logged-in users or the public is known as a global share permission.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None, however, a share permission is only returned for:   *  filters owned by the user.  *  filters shared with a group that the user is a member of.  *  filters shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.  *  filters shared with a public project.  *  filters shared with the public.
     */
    @Test
    public void getSharePermissionTest()  {
        Long id = null;
        Long permissionId = null;
        SharePermission response = api.getSharePermission(id, permissionId).block();

        // TODO: test validations
    }
    
    /**
     * Get share permissions
     *
     * Returns the share permissions for a filter. A filter can be shared with groups, projects, all logged-in users, or the public. Sharing with all logged-in users or the public is known as a global share permission.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None, however, share permissions are only returned for:   *  filters owned by the user.  *  filters shared with a group that the user is a member of.  *  filters shared with a private project that the user has *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for.  *  filters shared with a public project.  *  filters shared with the public.
     */
    @Test
    public void getSharePermissionsTest()  {
        Long id = null;
        List<SharePermission> response = api.getSharePermissions(id).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Set default share scope
     *
     * Sets the default sharing for new filters and dashboards for a user.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void setDefaultShareScopeTest()  {
        DefaultShareScope defaultShareScope = null;
        DefaultShareScope response = api.setDefaultShareScope(defaultShareScope).block();

        // TODO: test validations
    }
    
}
