/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.BulkCreateCustomFieldOptionRequest;
import com.atlassian.jira.rest.client.v2.model.BulkCustomFieldOptionCreateRequest;
import com.atlassian.jira.rest.client.v2.model.BulkCustomFieldOptionUpdateRequest;
import com.atlassian.jira.rest.client.v2.model.CustomFieldCreatedContextOptionsList;
import com.atlassian.jira.rest.client.v2.model.CustomFieldOption;
import com.atlassian.jira.rest.client.v2.model.CustomFieldUpdatedContextOptionsList;
import com.atlassian.jira.rest.client.v2.model.ErrorCollection;
import com.atlassian.jira.rest.client.v2.model.OrderOfCustomFieldOptions;
import com.atlassian.jira.rest.client.v2.model.PageBeanCustomFieldContextOption;
import com.atlassian.jira.rest.client.v2.model.PageBeanCustomFieldOptionDetails;
import com.atlassian.jira.rest.client.v2.model.UpdateCustomFieldOption;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssueCustomFieldOptionsApi
 */
@Ignore
public class IssueCustomFieldOptionsApiTest {

    private final IssueCustomFieldOptionsApi api = new IssueCustomFieldOptionsApi();

    
    /**
     * Create custom field options (context)
     *
     * Creates options and, where the custom select field is of the type Select List (cascading), cascading options for a custom select field. The options are added to a context of the field.  The maximum number of options that can be created per request is 1000 and each field can have a maximum of 10000 options.  This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createCustomFieldOptionTest()  {
        String fieldId = null;
        Long contextId = null;
        BulkCustomFieldOptionCreateRequest bulkCustomFieldOptionCreateRequest = null;
        CustomFieldCreatedContextOptionsList response = api.createCustomFieldOption(fieldId, contextId, bulkCustomFieldOptionCreateRequest).block();

        // TODO: test validations
    }
    
    /**
     * Create custom field options
     *
     * This operation is deprecated and becomes unavailable on 8 May 2021. Use [Create custom field options (context)](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-options/#api-rest-api-3-field-fieldid-context-contextid-option-post) instead. See [Deprecation of custom field options](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-removal-of-custom-field-options-operations/) for details.  Creates options and, where the custom select field is of the type *Select List (cascading)*, cascading options for a custom select field. The options are added to the global context of the field.  Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createCustomFieldOptionsTest()  {
        Long fieldId = null;
        BulkCreateCustomFieldOptionRequest bulkCreateCustomFieldOptionRequest = null;
        Object response = api.createCustomFieldOptions(fieldId, bulkCreateCustomFieldOptionRequest).block();

        // TODO: test validations
    }
    
    /**
     * Delete custom field options (context)
     *
     * Deletes a custom field option.  Options with cascading options cannot be deleted without deleting the cascading options first.  This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void deleteCustomFieldOptionTest()  {
        String fieldId = null;
        Long contextId = null;
        Long optionId = null;
        api.deleteCustomFieldOption(fieldId, contextId, optionId).block();

        // TODO: test validations
    }
    
    /**
     * Get custom field option
     *
     * This operation is deprecated and becomes unavailable on 8 May 2021. Use [Get custom field options (context)](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-options/#api-rest-api-3-field-fieldid-context-contextid-option-get) instead. See [Deprecation of custom field options](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-removal-of-custom-field-options-operations/) for details.  Returns a custom field option. For example, an option in a select list.  Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** The custom field option is returned as follows:   *  if the user has the *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).  *  if the user has the *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for at least one project the custom field is used in, and the field is visible in at least one layout the user has permission to view.
     */
    @Test
    public void getCustomFieldOptionTest()  {
        String id = null;
        CustomFieldOption response = api.getCustomFieldOption(id).block();

        // TODO: test validations
    }
    
    /**
     * Get custom field options (context)
     *
     * Returns a [paginated](#pagination) list of all custom field option for a context. Options are returned first then cascading options, in the order they display in Jira.  This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getOptionsForContextTest()  {
        String fieldId = null;
        Long contextId = null;
        Long optionId = null;
        Boolean onlyOptions = null;
        Long startAt = null;
        Integer maxResults = null;
        PageBeanCustomFieldContextOption response = api.getOptionsForContext(fieldId, contextId, optionId, onlyOptions, startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Get options for field
     *
     * This operation is deprecated and becomes unavailable on 8 May 2021. Use [Get custom field options (context)](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-options/#api-rest-api-3-field-fieldid-context-contextid-option-get) instead. See [Deprecation of custom field options](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-removal-of-custom-field-options-operations/) for details.  Returns a [paginated](#pagination) list of options and, where the custom select field is of the type *Select List (cascading)*, cascading options for custom select fields. Cascading options are included in the item count when determining pagination. Only options from the global context are returned.  Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getOptionsForFieldTest()  {
        Long fieldId = null;
        Long startAt = null;
        Integer maxResults = null;
        PageBeanCustomFieldOptionDetails response = api.getOptionsForField(fieldId, startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Reorder custom field options (context)
     *
     * Changes the order of custom field options or cascading options in a context.  This operation works for custom field options created in Jira or the operations from this resource. **To work with issue field select list options created for Connect apps use the [Issue custom field options (apps)](#api-group-issue-custom-field-options--apps-) operations.**  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void reorderCustomFieldOptionsTest()  {
        String fieldId = null;
        Long contextId = null;
        OrderOfCustomFieldOptions orderOfCustomFieldOptions = null;
        Object response = api.reorderCustomFieldOptions(fieldId, contextId, orderOfCustomFieldOptions).block();

        // TODO: test validations
    }
    
    /**
     * Update custom field options (context)
     *
     * Updates the options of a custom field.  If any of the options are not found, no options are updated. Options where the values in the request match the current values aren&#39;t updated and aren&#39;t reported in the response.  Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void updateCustomFieldOptionTest()  {
        String fieldId = null;
        Long contextId = null;
        BulkCustomFieldOptionUpdateRequest bulkCustomFieldOptionUpdateRequest = null;
        CustomFieldUpdatedContextOptionsList response = api.updateCustomFieldOption(fieldId, contextId, bulkCustomFieldOptionUpdateRequest).block();

        // TODO: test validations
    }
    
    /**
     * Update custom field options
     *
     * This operation is deprecated and becomes unavailable on 8 May 2021. Use [Update custom field options (context)](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-custom-field-options/#api-rest-api-3-field-fieldid-context-contextid-option-put) instead. See [Deprecation of custom field options](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-removal-of-custom-field-options-operations/) for details.  Updates the options on a custom select field. Where an updated option is in use on an issue, the value on the issue is also updated. Options that are not found are ignored. A maximum of 1000 options, including sub-options of *Select List (cascading)* fields, can be updated per request. The options are updated on the global context of the field.  Note that this operation **only works for issue field select list options created in Jira or using operations from the [Issue custom field options](#api-group-Issue-custom-field-options) resource**, it cannot be used with issue field select list options created by Connect apps.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void updateCustomFieldOptionsTest()  {
        Long fieldId = null;
        UpdateCustomFieldOption updateCustomFieldOption = null;
        Object response = api.updateCustomFieldOptions(fieldId, updateCustomFieldOption).block();

        // TODO: test validations
    }
    
}
