/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.IssueLinkType;
import com.atlassian.jira.rest.client.v2.model.IssueLinkTypes;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssueLinkTypesApi
 */
@Ignore
public class IssueLinkTypesApiTest {

    private final IssueLinkTypesApi api = new IssueLinkTypesApi();

    
    /**
     * Create issue link type
     *
     * Creates an issue link type. Use this operation to create descriptions of the reasons why issues are linked. The issue link type consists of a name and descriptions for a link&#39;s inward and outward relationships.  To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createIssueLinkTypeTest()  {
        IssueLinkType issueLinkType = null;
        IssueLinkType response = api.createIssueLinkType(issueLinkType).block();

        // TODO: test validations
    }
    
    /**
     * Delete issue link type
     *
     * Deletes an issue link type.  To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void deleteIssueLinkTypeTest()  {
        String issueLinkTypeId = null;
        api.deleteIssueLinkType(issueLinkTypeId).block();

        // TODO: test validations
    }
    
    /**
     * Get issue link type
     *
     * Returns an issue link type.  To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for a project in the site.
     */
    @Test
    public void getIssueLinkTypeTest()  {
        String issueLinkTypeId = null;
        IssueLinkType response = api.getIssueLinkType(issueLinkTypeId).block();

        // TODO: test validations
    }
    
    /**
     * Get issue link types
     *
     * Returns a list of all issue link types.  To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for a project in the site.
     */
    @Test
    public void getIssueLinkTypesTest()  {
        IssueLinkTypes response = api.getIssueLinkTypes().block();

        // TODO: test validations
    }
    
    /**
     * Update issue link type
     *
     * Updates an issue link type.  To use this operation, the site must have [issue linking](https://confluence.atlassian.com/x/yoXKM) enabled.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void updateIssueLinkTypeTest()  {
        String issueLinkTypeId = null;
        IssueLinkType issueLinkType = null;
        IssueLinkType response = api.updateIssueLinkType(issueLinkTypeId, issueLinkType).block();

        // TODO: test validations
    }
    
}
