/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.CreatedIssue;
import com.atlassian.jira.rest.client.v2.model.CreatedIssues;
import com.atlassian.jira.rest.client.v2.model.ErrorCollection;
import com.atlassian.jira.rest.client.v2.model.IssueBean;
import com.atlassian.jira.rest.client.v2.model.IssueCreateMetadata;
import com.atlassian.jira.rest.client.v2.model.IssueUpdateMetadata;
import com.atlassian.jira.rest.client.v2.model.PageBeanChangelog;
import com.atlassian.jira.rest.client.v2.model.Transitions;
import com.atlassian.jira.rest.client.v2.model.User;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssuesApi
 */
@Ignore
public class IssuesApiTest {

    private final IssuesApi api = new IssuesApi();

    
    /**
     * Assign issue
     *
     * Assigns an issue to a user. Use this operation when the calling user does not have the *Edit Issues* permission but has the *Assign issue* permission for the project that the issue is in.  If &#x60;name&#x60; or &#x60;accountId&#x60; is set to:   *  &#x60;\&quot;-1\&quot;&#x60;, the issue is assigned to the default assignee for the project.  *  &#x60;null&#x60;, the issue is set to unassigned.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse Projects* and *Assign Issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void assignIssueTest()  {
        String issueIdOrKey = null;
        User user = null;
        Object response = api.assignIssue(issueIdOrKey, user).block();

        // TODO: test validations
    }
    
    /**
     * Create issue
     *
     * Creates an issue or, where the option to create subtasks is enabled in Jira, a subtask. A transition may be applied, to move the issue or subtask to a workflow step other than the default start step, and issue properties set.  The content of the issue or subtask is defined using &#x60;update&#x60; and &#x60;fields&#x60;. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get). These are the same fields that appear on the issue&#39;s create screen.  Creating a subtask differs from creating an issue as follows:   *  &#x60;issueType&#x60; must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get) to find subtask issue types).  *  &#x60;parent&#x60; must contain the ID or key of the parent issue.  **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which the issue or subtask is created.
     */
    @Test
    public void createIssueTest()  {
        Map<String, Object> requestBody = null;
        Boolean updateHistory = null;
        CreatedIssue response = api.createIssue(requestBody, updateHistory).block();

        // TODO: test validations
    }
    
    /**
     * Bulk create issue
     *
     * Creates issues and, where the option to create subtasks is enabled in Jira, subtasks. Transitions may be applied, to move the issues or subtasks to a workflow step other than the default start step, and issue properties set.  The content of each issue or subtask is defined using &#x60;update&#x60; and &#x60;fields&#x60;. The fields that can be set in the issue or subtask are determined using the [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get). These are the same fields that appear on the issues&#39; create screens.  Creating a subtask differs from creating an issue as follows:   *  &#x60;issueType&#x60; must be set to a subtask issue type (use [ Get create issue metadata](#api-rest-api-2-issue-createmeta-get) to find subtask issue types).  *  &#x60;parent&#x60; the must contain the ID or key of the parent issue.  **[Permissions](#permissions) required:** *Browse projects* and *Create issues* [project permissions](https://confluence.atlassian.com/x/yodKLg) for the project in which each issue or subtask is created.
     */
    @Test
    public void createIssuesTest()  {
        Map<String, Object> requestBody = null;
        CreatedIssues response = api.createIssues(requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Delete issue
     *
     * Deletes an issue.  An issue cannot be deleted if it has one or more subtasks. To delete an issue with subtasks, set &#x60;deleteSubtasks&#x60;. This causes the issue&#39;s subtasks to be deleted with the issue.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* and *Delete issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project containing the issue.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void deleteIssueTest()  {
        String issueIdOrKey = null;
        String deleteSubtasks = null;
        api.deleteIssue(issueIdOrKey, deleteSubtasks).block();

        // TODO: test validations
    }
    
    /**
     * Transition issue
     *
     * Performs an issue transition and, if the transition has a screen, updates the fields from the transition screen.  sortByCategory To update the fields on the transition screen, specify the fields in the &#x60;fields&#x60; or &#x60;update&#x60; parameters in the request body. Get details about the fields using [ Get transitions](#api-rest-api-2-issue-issueIdOrKey-transitions-get) with the &#x60;transitions.fields&#x60; expand.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* and *Transition issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void doTransitionTest()  {
        String issueIdOrKey = null;
        Map<String, Object> requestBody = null;
        Object response = api.doTransition(issueIdOrKey, requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Edit issue
     *
     * Edits an issue. A transition may be applied and issue properties updated as part of the edit.  The edits to the issue&#39;s fields are defined using &#x60;update&#x60; and &#x60;fields&#x60;. The fields that can be edited are determined using [ Get edit issue metadata](#api-rest-api-2-issue-issueIdOrKey-editmeta-get).  The parent field may be set by key or ID. For standard issue types, the parent may be removed by setting &#x60;update.parent.set.none&#x60; to *true*.  Connect app users with admin permissions (from user permissions and app scopes) can override the screen security configuration using &#x60;overrideScreenSecurity&#x60; and &#x60;overrideEditableFlag&#x60;.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* and *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void editIssueTest()  {
        String issueIdOrKey = null;
        Map<String, Object> requestBody = null;
        Boolean notifyUsers = null;
        Boolean overrideScreenSecurity = null;
        Boolean overrideEditableFlag = null;
        Object response = api.editIssue(issueIdOrKey, requestBody, notifyUsers, overrideScreenSecurity, overrideEditableFlag).block();

        // TODO: test validations
    }
    
    /**
     * Get change logs
     *
     * Returns a [paginated](#pagination) list of all changelogs for an issue sorted by date, starting from the oldest.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void getChangeLogsTest()  {
        String issueIdOrKey = null;
        Integer startAt = null;
        Integer maxResults = null;
        PageBeanChangelog response = api.getChangeLogs(issueIdOrKey, startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Get create issue metadata
     *
     * Returns details of projects, issue types within projects, and, when requested, the create screen fields for each issue type for the user. Use the information to populate the requests in [ Create issue](#api-rest-api-2-issue-post) and [Create issues](#api-rest-api-2-issue-bulk-post).  The request can be restricted to specific projects or issue types using the query parameters. The response will contain information for the valid projects, issue types, or project and issue type combinations requested. Note that invalid project, issue type, or project and issue type combinations do not generate errors.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** *Create issues* [project permission](https://confluence.atlassian.com/x/yodKLg) in the requested projects.
     */
    @Test
    public void getCreateIssueMetaTest()  {
        List<String> projectIds = null;
        List<String> projectKeys = null;
        List<String> issuetypeIds = null;
        List<String> issuetypeNames = null;
        String expand = null;
        IssueCreateMetadata response = api.getCreateIssueMeta(projectIds, projectKeys, issuetypeIds, issuetypeNames, expand).block();

        // TODO: test validations
    }
    
    /**
     * Get edit issue metadata
     *
     * Returns the edit screen fields for an issue that are visible to and editable by the user. Use the information to populate the requests in [Edit issue](#api-rest-api-2-issue-issueIdOrKey-put).  Connect app users with admin permissions (from user permissions and app scopes) can return additional details using:   *  &#x60;overrideScreenSecurity&#x60; Returns hidden fields.  *  &#x60;overrideEditableFlag&#x60; Returns uneditable fields. For example, where an issue has a workflow status of closed none of its fields are editable.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.  Note: For any fields to be editable the user must have the *Edit issues* [project permission](https://confluence.atlassian.com/x/yodKLg) for the issue.
     */
    @Test
    public void getEditIssueMetaTest()  {
        String issueIdOrKey = null;
        Boolean overrideScreenSecurity = null;
        Boolean overrideEditableFlag = null;
        IssueUpdateMetadata response = api.getEditIssueMeta(issueIdOrKey, overrideScreenSecurity, overrideEditableFlag).block();

        // TODO: test validations
    }
    
    /**
     * Get issue
     *
     * Returns the details for an issue.  The issue is identified by its ID or key, however, if the identifier doesn&#39;t match an issue, a case-insensitive search and check for moved issues is performed. If a matching issue is found its details are returned, a 302 or other redirect is **not** returned. The issue key returned in the response is the key of the issue found.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void getIssueTest()  {
        String issueIdOrKey = null;
        List<String> fields = null;
        Boolean fieldsByKeys = null;
        String expand = null;
        List<String> properties = null;
        Boolean updateHistory = null;
        IssueBean response = api.getIssue(issueIdOrKey, fields, fieldsByKeys, expand, properties, updateHistory).block();

        // TODO: test validations
    }
    
    /**
     * Get transitions
     *
     * Returns either all transitions or a transition that can be performed by the user on an issue, based on the issue&#39;s status.  Note, if a request is made for a transition that does not exist or cannot be performed on the issue, given its status, the response will return any empty transitions list.  This operation can be accessed anonymously.  **[Permissions](#permissions) required: A list or transition is returned only when the user has:**   *  *Browse projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.  However, if the user does not have the *Transition issues* [ project permission](https://confluence.atlassian.com/x/yodKLg) the response will not list any transitions.
     */
    @Test
    public void getTransitionsTest()  {
        String issueIdOrKey = null;
        String expand = null;
        String transitionId = null;
        Boolean skipRemoteOnlyCondition = null;
        Boolean includeUnavailableTransitions = null;
        Boolean sortByOpsBarAndStatus = null;
        Transitions response = api.getTransitions(issueIdOrKey, expand, transitionId, skipRemoteOnlyCondition, includeUnavailableTransitions, sortByOpsBarAndStatus).block();

        // TODO: test validations
    }
    
    /**
     * Send notification for issue
     *
     * Creates an email notification for an issue and adds it to the mail queue.  **[Permissions](#permissions) required:**   *  *Browse Projects* [project permission](https://confluence.atlassian.com/x/yodKLg) for the project that the issue is in.  *  If [issue-level security](https://confluence.atlassian.com/x/J4lKLg) is configured, issue-level security permission to view the issue.
     */
    @Test
    public void notifyTest()  {
        String issueIdOrKey = null;
        Map<String, Object> requestBody = null;
        Object response = api.notify(issueIdOrKey, requestBody).block();

        // TODO: test validations
    }
    
}
