/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.IssueTypeIds;
import com.atlassian.jira.rest.client.v2.model.IssueTypeScreenSchemeDetails;
import com.atlassian.jira.rest.client.v2.model.IssueTypeScreenSchemeId;
import com.atlassian.jira.rest.client.v2.model.IssueTypeScreenSchemeMappingDetails;
import com.atlassian.jira.rest.client.v2.model.IssueTypeScreenSchemeProjectAssociation;
import com.atlassian.jira.rest.client.v2.model.IssueTypeScreenSchemeUpdateDetails;
import com.atlassian.jira.rest.client.v2.model.PageBeanIssueTypeScreenScheme;
import com.atlassian.jira.rest.client.v2.model.PageBeanIssueTypeScreenSchemeItem;
import com.atlassian.jira.rest.client.v2.model.PageBeanIssueTypeScreenSchemesProjects;
import java.util.Set;
import com.atlassian.jira.rest.client.v2.model.UpdateDefaultScreenScheme;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssueTypeScreenSchemesApi
 */
@Ignore
public class IssueTypeScreenSchemesApiTest {

    private final IssueTypeScreenSchemesApi api = new IssueTypeScreenSchemesApi();

    
    /**
     * Append mappings to issue type screen scheme
     *
     * Appends issue type to screen scheme mappings to an issue type screen scheme.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void appendMappingsForIssueTypeScreenSchemeTest()  {
        String issueTypeScreenSchemeId = null;
        IssueTypeScreenSchemeMappingDetails issueTypeScreenSchemeMappingDetails = null;
        Object response = api.appendMappingsForIssueTypeScreenScheme(issueTypeScreenSchemeId, issueTypeScreenSchemeMappingDetails).block();

        // TODO: test validations
    }
    
    /**
     * Assign issue type screen scheme to project
     *
     * Assigns an issue type screen scheme to a project.  Issue type screen schemes can only be assigned to classic projects.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void assignIssueTypeScreenSchemeToProjectTest()  {
        IssueTypeScreenSchemeProjectAssociation issueTypeScreenSchemeProjectAssociation = null;
        Object response = api.assignIssueTypeScreenSchemeToProject(issueTypeScreenSchemeProjectAssociation).block();

        // TODO: test validations
    }
    
    /**
     * Create issue type screen scheme
     *
     * Creates an issue type screen scheme.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createIssueTypeScreenSchemeTest()  {
        IssueTypeScreenSchemeDetails issueTypeScreenSchemeDetails = null;
        IssueTypeScreenSchemeId response = api.createIssueTypeScreenScheme(issueTypeScreenSchemeDetails).block();

        // TODO: test validations
    }
    
    /**
     * Delete issue type screen scheme
     *
     * Deletes an issue type screen scheme.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void deleteIssueTypeScreenSchemeTest()  {
        String issueTypeScreenSchemeId = null;
        Object response = api.deleteIssueTypeScreenScheme(issueTypeScreenSchemeId).block();

        // TODO: test validations
    }
    
    /**
     * Get issue type screen scheme items
     *
     * Returns a [paginated](#pagination) list of issue type screen scheme items.  Only issue type screen schemes used in classic projects are returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getIssueTypeScreenSchemeMappingsTest()  {
        Long startAt = null;
        Integer maxResults = null;
        Set<Long> issueTypeScreenSchemeId = null;
        PageBeanIssueTypeScreenSchemeItem response = api.getIssueTypeScreenSchemeMappings(startAt, maxResults, issueTypeScreenSchemeId).block();

        // TODO: test validations
    }
    
    /**
     * Get issue type screen schemes for projects
     *
     * Returns a [paginated](#pagination) list of issue type screen schemes and, for each issue type screen scheme, a list of the projects that use it.  Only issue type screen schemes used in classic projects are returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getIssueTypeScreenSchemeProjectAssociationsTest()  {
        Set<Long> projectId = null;
        Long startAt = null;
        Integer maxResults = null;
        PageBeanIssueTypeScreenSchemesProjects response = api.getIssueTypeScreenSchemeProjectAssociations(projectId, startAt, maxResults).block();

        // TODO: test validations
    }
    
    /**
     * Get issue type screen schemes
     *
     * Returns a [paginated](#pagination) list of issue type screen schemes.  Only issue type screen schemes used in classic projects are returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getIssueTypeScreenSchemesTest()  {
        Long startAt = null;
        Integer maxResults = null;
        Set<Long> id = null;
        PageBeanIssueTypeScreenScheme response = api.getIssueTypeScreenSchemes(startAt, maxResults, id).block();

        // TODO: test validations
    }
    
    /**
     * Remove mappings from issue type screen scheme
     *
     * Removes issue type to screen scheme mappings from an issue type screen scheme.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void removeMappingsFromIssueTypeScreenSchemeTest()  {
        String issueTypeScreenSchemeId = null;
        IssueTypeIds issueTypeIds = null;
        Object response = api.removeMappingsFromIssueTypeScreenScheme(issueTypeScreenSchemeId, issueTypeIds).block();

        // TODO: test validations
    }
    
    /**
     * Update issue type screen scheme default screen scheme
     *
     * Updates the default screen scheme of an issue type screen scheme. The default screen scheme is used for all unmapped issue types.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void updateDefaultScreenSchemeTest()  {
        String issueTypeScreenSchemeId = null;
        UpdateDefaultScreenScheme updateDefaultScreenScheme = null;
        Object response = api.updateDefaultScreenScheme(issueTypeScreenSchemeId, updateDefaultScreenScheme).block();

        // TODO: test validations
    }
    
    /**
     * Update issue type screen scheme
     *
     * Updates an issue type screen scheme.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void updateIssueTypeScreenSchemeTest()  {
        String issueTypeScreenSchemeId = null;
        IssueTypeScreenSchemeUpdateDetails issueTypeScreenSchemeUpdateDetails = null;
        Object response = api.updateIssueTypeScreenScheme(issueTypeScreenSchemeId, issueTypeScreenSchemeUpdateDetails).block();

        // TODO: test validations
    }
    
}
