/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.ProjectFeatureToggleRequest;
import com.atlassian.jira.rest.client.v2.model.ProjectFeaturesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectFeaturesApi
 */
@Ignore
public class ProjectFeaturesApiTest {

    private final ProjectFeaturesApi api = new ProjectFeaturesApi();

    
    /**
     * Get features for project
     *
     * Returns the list of features for a project. The project must be a [company-managed](https://support.atlassian.com/jira-service-management-cloud/docs/learn-the-differences-between-classic-and-next-gen-projects/) project.
     */
    @Test
    public void getFeaturesForProjectTest()  {
        String projectIdOrKey = null;
        ProjectFeaturesResponse response = api.getFeaturesForProject(projectIdOrKey).block();

        // TODO: test validations
    }
    
    /**
     * Toggle feature for project
     *
     * Changes the state of a feature to ENABLED or DISABLED for the project. The project must be a [company-managed](https://support.atlassian.com/jira-service-management-cloud/docs/learn-the-differences-between-classic-and-next-gen-projects/) project.
     */
    @Test
    public void toggleFeatureForProjectTest()  {
        String projectIdOrKey = null;
        String featureKey = null;
        ProjectFeatureToggleRequest projectFeatureToggleRequest = null;
        ProjectFeaturesResponse response = api.toggleFeatureForProject(projectIdOrKey, featureKey, projectFeatureToggleRequest).block();

        // TODO: test validations
    }
    
}
