/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.ProjectType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProjectTypesApi
 */
@Ignore
public class ProjectTypesApiTest {

    private final ProjectTypesApi api = new ProjectTypesApi();

    
    /**
     * Get accessible project type by key
     *
     * Returns a [project type](https://confluence.atlassian.com/x/Var1Nw) if it is accessible to the user.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void getAccessibleProjectTypeByKeyTest()  {
        String projectTypeKey = null;
        ProjectType response = api.getAccessibleProjectTypeByKey(projectTypeKey).block();

        // TODO: test validations
    }
    
    /**
     * Get licensed project types
     *
     * Returns all [project types](https://confluence.atlassian.com/x/Var1Nw) with a valid license.
     */
    @Test
    public void getAllAccessibleProjectTypesTest()  {
        List<ProjectType> response = api.getAllAccessibleProjectTypes().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get all project types
     *
     * Returns all [project types](https://confluence.atlassian.com/x/Var1Nw), whether or not the instance has a valid license for each type.  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     */
    @Test
    public void getAllProjectTypesTest()  {
        List<ProjectType> response = api.getAllProjectTypes().collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get project type by key
     *
     * Returns a [project type](https://confluence.atlassian.com/x/Var1Nw).  This operation can be accessed anonymously.  **[Permissions](#permissions) required:** None.
     */
    @Test
    public void getProjectTypeByKeyTest()  {
        String projectTypeKey = null;
        ProjectType response = api.getProjectTypeByKey(projectTypeKey).block();

        // TODO: test validations
    }
    
}
