/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.PageBeanScreen;
import com.atlassian.jira.rest.client.v2.model.PageBeanScreenWithTab;
import com.atlassian.jira.rest.client.v2.model.Screen;
import com.atlassian.jira.rest.client.v2.model.ScreenDetails;
import com.atlassian.jira.rest.client.v2.model.ScreenableField;
import java.util.Set;
import com.atlassian.jira.rest.client.v2.model.UpdateScreenDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ScreensApi
 */
@Ignore
public class ScreensApiTest {

    private final ScreensApi api = new ScreensApi();

    
    /**
     * Add field to default screen
     *
     * Adds a field to the default tab of the default screen.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void addFieldToDefaultScreenTest()  {
        String fieldId = null;
        Object response = api.addFieldToDefaultScreen(fieldId).block();

        // TODO: test validations
    }
    
    /**
     * Create screen
     *
     * Creates a screen with a default field tab.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createScreenTest()  {
        ScreenDetails screenDetails = null;
        Screen response = api.createScreen(screenDetails).block();

        // TODO: test validations
    }
    
    /**
     * Delete screen
     *
     * Deletes a screen. A screen cannot be deleted if it is used in a screen scheme, workflow, or workflow draft.  Only screens used in classic projects can be deleted.
     */
    @Test
    public void deleteScreenTest()  {
        Long screenId = null;
        api.deleteScreen(screenId).block();

        // TODO: test validations
    }
    
    /**
     * Get available screen fields
     *
     * Returns the fields that can be added to a tab on a screen.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getAvailableScreenFieldsTest()  {
        Long screenId = null;
        List<ScreenableField> response = api.getAvailableScreenFields(screenId).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get screens
     *
     * Returns a [paginated](#pagination) list of all screens or those specified by one or more screen IDs.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getScreensTest()  {
        Long startAt = null;
        Integer maxResults = null;
        Set<Long> id = null;
        PageBeanScreen response = api.getScreens(startAt, maxResults, id).block();

        // TODO: test validations
    }
    
    /**
     * Get screens for a field
     *
     * Returns a [paginated](#pagination) list of the screens a field is used in.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getScreensForFieldTest()  {
        String fieldId = null;
        Long startAt = null;
        Integer maxResults = null;
        String expand = null;
        PageBeanScreenWithTab response = api.getScreensForField(fieldId, startAt, maxResults, expand).block();

        // TODO: test validations
    }
    
    /**
     * Update screen
     *
     * Updates a screen. Only screens used in classic projects can be updated.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void updateScreenTest()  {
        Long screenId = null;
        UpdateScreenDetails updateScreenDetails = null;
        Screen response = api.updateScreen(screenId, updateScreenDetails).block();

        // TODO: test validations
    }
    
}
