/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.ColumnItem;
import com.atlassian.jira.rest.client.v2.model.GroupName;
import com.atlassian.jira.rest.client.v2.model.PageBeanUser;
import com.atlassian.jira.rest.client.v2.model.UnrestrictedUserEmail;
import com.atlassian.jira.rest.client.v2.model.User;
import com.atlassian.jira.rest.client.v2.model.UserMigrationBean;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Ignore
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    
    /**
     * Bulk get users
     *
     * Returns a [paginated](#pagination) list of the users specified by one or more account IDs.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void bulkGetUsersTest()  {
        List<String> accountId = null;
        Long startAt = null;
        Integer maxResults = null;
        List<String> username = null;
        List<String> key = null;
        PageBeanUser response = api.bulkGetUsers(accountId, startAt, maxResults, username, key).block();

        // TODO: test validations
    }
    
    /**
     * Get account IDs for users
     *
     * Returns the account IDs for the users specified in the &#x60;key&#x60; or &#x60;username&#x60; parameters. Note that multiple &#x60;key&#x60; or &#x60;username&#x60; parameters can be specified.  **[Permissions](#permissions) required:** Permission to access Jira.
     */
    @Test
    public void bulkGetUsersMigrationTest()  {
        Long startAt = null;
        Integer maxResults = null;
        List<String> username = null;
        List<String> key = null;
        List<UserMigrationBean> response = api.bulkGetUsersMigration(startAt, maxResults, username, key).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Create user
     *
     * Creates a user. This resource is retained for legacy compatibility. As soon as a more suitable alternative is available this resource will be deprecated.  If the user exists and has access to Jira, the operation returns a 201 status. If the user exists but does not have access to Jira, the operation returns a 400 status.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createUserTest()  {
        Map<String, Object> requestBody = null;
        User response = api.createUser(requestBody).block();

        // TODO: test validations
    }
    
    /**
     * Get all users
     *
     * Returns a list of all (active and inactive) users.  **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getAllUsersTest()  {
        Integer startAt = null;
        Integer maxResults = null;
        List<User> response = api.getAllUsers(startAt, maxResults).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get all users default
     *
     * Returns a list of all (active and inactive) users.  **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getAllUsersDefaultTest()  {
        Integer startAt = null;
        Integer maxResults = null;
        List<User> response = api.getAllUsersDefault(startAt, maxResults).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get user
     *
     * Returns a user.  **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getUserTest()  {
        String accountId = null;
        String username = null;
        String key = null;
        String expand = null;
        User response = api.getUser(accountId, username, key, expand).block();

        // TODO: test validations
    }
    
    /**
     * Get user default columns
     *
     * Returns the default [issue table columns](https://confluence.atlassian.com/x/XYdKLg) for the user. If &#x60;accountId&#x60; is not passed in the request, the calling user&#39;s details are returned.  **[Permissions](#permissions) required:**   *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLgl), to get the column details for any user.  *  Permission to access Jira, to get the calling user&#39;s column details.
     */
    @Test
    public void getUserDefaultColumnsTest()  {
        String accountId = null;
        String username = null;
        List<ColumnItem> response = api.getUserDefaultColumns(accountId, username).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get user email
     *
     * Returns a user&#39;s email address. This API is only available to apps approved by Atlassian, according to these [guidelines](https://community.developer.atlassian.com/t/guidelines-for-requesting-access-to-email-address/27603).
     */
    @Test
    public void getUserEmailTest()  {
        String accountId = null;
        UnrestrictedUserEmail response = api.getUserEmail(accountId).block();

        // TODO: test validations
    }
    
    /**
     * Get user email bulk
     *
     * Returns a user&#39;s email address. This API is only available to apps approved by Atlassian, according to these [guidelines](https://community.developer.atlassian.com/t/guidelines-for-requesting-access-to-email-address/27603).
     */
    @Test
    public void getUserEmailBulkTest()  {
        List<String> accountId = null;
        UnrestrictedUserEmail response = api.getUserEmailBulk(accountId).block();

        // TODO: test validations
    }
    
    /**
     * Get user groups
     *
     * Returns the groups to which a user belongs.  **[Permissions](#permissions) required:** *Browse users and groups* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getUserGroupsTest()  {
        String accountId = null;
        String username = null;
        String key = null;
        List<GroupName> response = api.getUserGroups(accountId, username, key).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Delete user
     *
     * Deletes a user.  **[Permissions](#permissions) required:** Site administration (that is, membership of the *site-admin* [group](https://confluence.atlassian.com/x/24xjL)).
     */
    @Test
    public void removeUserTest()  {
        String accountId = null;
        String username = null;
        String key = null;
        api.removeUser(accountId, username, key).block();

        // TODO: test validations
    }
    
    /**
     * Reset user default columns
     *
     * Resets the default [ issue table columns](https://confluence.atlassian.com/x/XYdKLg) for the user to the system default. If &#x60;accountId&#x60; is not passed, the calling user&#39;s default columns are reset.  **[Permissions](#permissions) required:**   *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), to set the columns on any user.  *  Permission to access Jira, to set the calling user&#39;s columns.
     */
    @Test
    public void resetUserColumnsTest()  {
        String accountId = null;
        String username = null;
        api.resetUserColumns(accountId, username).block();

        // TODO: test validations
    }
    
    /**
     * Set user default columns
     *
     * Sets the default [ issue table columns](https://confluence.atlassian.com/x/XYdKLg) for the user. If an account ID is not passed, the calling user&#39;s default columns are set. If no column details are sent, then all default columns are removed.  The parameters for this resource are expressed as HTML form data. For example, in curl:  &#x60;curl -X PUT -d columns&#x3D;summary -d columns&#x3D;description https://your-domain.atlassian.net/rest/api/2/user/columns?accountId&#x3D;5b10ac8d82e05b22cc7d4ef5&#39;&#x60;  **[Permissions](#permissions) required:**   *  *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg), to set the columns on any user.  *  Permission to access Jira, to set the calling user&#39;s columns.
     */
    @Test
    public void setUserColumnsTest()  {
        String accountId = null;
        List<String> requestBody = null;
        Object response = api.setUserColumns(accountId, requestBody).block();

        // TODO: test validations
    }
    
}
