/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.atlassian.jira.rest.client.v2.api;

import com.atlassian.jira.rest.client.v2.model.CreateWorkflowDetails;
import com.atlassian.jira.rest.client.v2.model.DeprecatedWorkflow;
import com.atlassian.jira.rest.client.v2.model.ErrorCollection;
import com.atlassian.jira.rest.client.v2.model.PageBeanWorkflow;
import java.util.Set;
import com.atlassian.jira.rest.client.v2.model.WorkflowID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WorkflowsApi
 */
@Ignore
public class WorkflowsApiTest {

    private final WorkflowsApi api = new WorkflowsApi();

    
    /**
     * Create workflow
     *
     * Creates a workflow. Workflow transitions are created with the default system transition rules.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void createWorkflowTest()  {
        CreateWorkflowDetails createWorkflowDetails = null;
        WorkflowID response = api.createWorkflow(createWorkflowDetails).block();

        // TODO: test validations
    }
    
    /**
     * Delete inactive workflow
     *
     * Deletes a workflow.  The workflow cannot be deleted if it is:   *  an active workflow.  *  a system workflow.  *  associated with any workflow scheme.  *  associated with any draft workflow scheme.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void deleteInactiveWorkflowTest()  {
        String entityId = null;
        api.deleteInactiveWorkflow(entityId).block();

        // TODO: test validations
    }
    
    /**
     * Get all workflows
     *
     * Returns all workflows in Jira or a workflow. Deprecated, use [Get workflows paginated](#api-rest-api-2-workflow-search-get).  If the &#x60;workflowName&#x60; parameter is specified, the workflow is returned as an object (not in an array). Otherwise, an array of workflow objects is returned.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getAllWorkflowsTest()  {
        String workflowName = null;
        List<DeprecatedWorkflow> response = api.getAllWorkflows(workflowName).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get workflows paginated
     *
     * Returns a [paginated](#pagination) list of published classic workflows. When workflow names are specified, details of those workflows are returned. Otherwise, all published classic workflows are returned.  This operation does not return next-gen workflows.  **[Permissions](#permissions) required:** *Administer Jira* [global permission](https://confluence.atlassian.com/x/x4dKLg).
     */
    @Test
    public void getWorkflowsPaginatedTest()  {
        Long startAt = null;
        Integer maxResults = null;
        Set<String> workflowName = null;
        String expand = null;
        PageBeanWorkflow response = api.getWorkflowsPaginated(startAt, maxResults, workflowName, expand).block();

        // TODO: test validations
    }
    
}
